### ISSUE TITLE
Revamp ludwig.ai home page

### ISSUE THREAD

**Issue by justinxzhao** [ludwig-ai/ludwig-docs#201]

**Comment by martindavis** [comment]
Yassss! Based on my experience a few months ago @justinxzhao , our biggest question to answer before we can move forward with this: can we get our current docs system to create the website we want? I think the latest version/upgrades will do that, but we have to try it out and see what we can do.

From there, it's then a question of do we want to continue to use Github Pages or host this on say AWS?
