### ISSUE TITLE
Typo in `src/docs/getting_started.md`

### ISSUE THREAD

**Issue by d4mr** [ludwig-ai/ludwig-docs#25]
Line 25 of [getting_started.md](https://github.com/ludwig-ai/ludwig-docs/blob/master/src/docs/getting_started.md#L25)

>but udwig provides standard visualizations to understand their performance and compare their predictions.

Should be:
>but Ludwig provides standard visualizations to understand their performance and compare their predictions.

**Comment by w4nderlust** [comment]
Solved, thank you!
