### ISSUE TITLE
Missing section on website

### ISSUE THREAD

**Issue by carlogrisetti** [ludwig-ai/ludwig-docs#34]
Seems to me that an entire section disappeared, like all the training documentation in the user guide, with all the features and various description of encoders\decoders\combiners\etc

**Comment by w4nderlust** [comment]
Right now it is all here I believe: https://ludwig-ai.github.io/ludwig-docs/user_guide/configuration/
Although we are planning to further split it in multiple subpages.
The pig user guide page we had before was becoming to big an heacy to load ;)

**Comment by carlogrisetti** [comment]
Oh I couldn't find it and the sidebar nav was so useful. Please consider adding the navigation tree back, as it meant a much faster navigation towards the specific feature parameter you are looking for and always forget :)

**Comment by w4nderlust** [comment]
It's still there on the right, isn't it?
<img width="1202" alt="Schermata 2021-07-12 alle 14 57 25" src="https://user-images.githubusercontent.com/349256/125360983-86cdeb00-e321-11eb-95f3-304b2f5b013d.png">

**Comment by carlogrisetti** [comment]
Damn I couldn't see it... Maybe my fault due to some RPA testing I was doing on Chrome.

Sorry to bother :)
