### ISSUE TITLE
Need to update supported output loss types for numerical features

### ISSUE THREAD

**Issue by amholler** [ludwig-ai/ludwig-docs#35]
The doc says this about the supported output loss types for numerical features:

loss (default {type: mean_squared_error}): is a dictionary containing a loss type. The available losses type are mean_squared_error and mean_absolute_error.

In the source code, we see that root_mean_squared_error is also supported.  @w4nderlust suggest to file an issue
to track updating this.

**Comment by dantreiman** [comment]
Verified fixed in 0.4 and 0.5, closing.
