### ISSUE TITLE
Update Transformer Combiner parameter doc for reduce_output

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig-docs#38]
For Transformer Combiner, `reduce_output` parameter missing `None` as valid value.

See [discussion](https://ludwig-ai.slack.com/archives/C02CK64TKGQ/p1633198058122700)

**Comment by dantreiman** [comment]
Fixed in 0.5 by https://github.com/ludwig-ai/ludwig-docs/pull/63
