### ISSUE TITLE
Missing TabTransformer Combiner description

### ISSUE THREAD

**Issue by jimthompson5802** [ludwig-ai/ludwig-docs#39]
Missing write up for the `TabTransformerCombiner`

https://ludwig-ai.github.io/ludwig-docs/user_guide/configuration/#combiners

![image](https://user-images.githubusercontent.com/1425269/136134333-5b24c5b9-4c92-4094-994b-b1683687584a.png)

To be included in the doc:
*  When we cite the paper in the docs we can say that this implementation "is inspired by the one presented in [citation]( https://arxiv.org/abs/2012.06678), but is generalized to additional data types".

**Comment by w4nderlust** [comment]
Addressed by #123
