### ISSUE TITLE
Potential typo? "reduced_output" in the Text Features section

### ISSUE THREAD

**Issue by louixs** [ludwig-ai/ludwig-docs#40]
Hi!

First of all thanks for this amazing package. 
While I was going through the docs, I just noticed that in the Text Features section in Configuration, "reduced_output" is used whereas other section is using "reduce_output".

It looks like a typo but I wasn't sure if it was intentional due to some reasons I'm not aware of. I searched for "reduced_output" in the Ludwig code base just in case but didn't return any match. So I'm reasonably sure it is just a typo.

Here's a section in the docs where you can see it. Although I can see that "reduced_output" is used through out the text_features .
https://github.com/ludwig-ai/ludwig-docs/blob/e2e1bcfa556e145e49f634998dd37cf84a629da1/src/docs/user_guide/configuration/text_features.md#L215

Would it be possible to ask someone, who's more familiar with this, to confirm whether it is a typo? If confirmed, and if you don't mind I'd be happy to fix it and open a pull request as well :)

Thanks

**Comment by w4nderlust** [comment]
@louixs, great catch! it's actually `reduce_output`. Feel free to submit a PR, and please change only the Markdown files not the html ones ;)

**Comment by louixs** [comment]
Hi @w4nderlust!

Many thanks for confirming as well as for encouraging to submit a PR! I've just done so as you can see above :)

I did my best to double check that everything is ok with the fix but please let me know if there is any issue!

All the best.

**Comment by w4nderlust** [comment]
Thanks @louixs , PR merged!

**Comment by louixs** [comment]
Awesome. Thanks @w4nderlust!
