### ISSUE TITLE
Link text style is too similar to normal paragraph text, particularly in dark mode

### ISSUE THREAD

**Issue by dantreiman** [ludwig-ai/ludwig-docs#53]
I don't think links have enough contrast from regular text, particularly on touch devices which have no hover.

My recommendation would be to underline all links, but open to other ideas.

Light (Links are gray, but IMO more contrast would be better):
<img width="856" alt="Screen Shot 2022-02-24 at 1 08 47 PM" src="https://user-images.githubusercontent.com/687280/155608110-ae065f1b-6667-4179-b3b3-156f90e7538a.png">

Dark (I can't tell the difference between links and regular bold text):
<img width="856" alt="Screen Shot 2022-02-24 at 1 08 40 PM" src="https://user-images.githubusercontent.com/687280/155608115-59acd5eb-d37e-451b-bb8b-37a0c8837545.png">

**Comment by justinxzhao** [comment]
I also find the bolded links contrast to be insufficient. +1 to underlining.
